apiVersion: batch/v1
kind: Job
metadata:
  name: st2-virtualenvs-efs-provision
  namespace: stackstorm
spec:
  template:
    metadata:
      name: st2-virtualenvs-efs-provision
    spec:
      containers:
      - name: st2-virtualenvs-efs-provision
        image: busybox
        command: [ "sh", "-c", "mkdir -p /efs/volumes/static/st2-virtualenvs && cd /efs/volumes/static && addgroup ubuntu && chown root:ubuntu st2-virtualenvs && chmod 770 st2-virtualenvs" ]
        volumeMounts:
          - name: "st2-virtualenvs-efs-provision"
            mountPath: "/efs"
      volumes:
        - name: st2-virtualenvs-efs-provision
          nfs:
            server: fs-xxxxxxxx.efs.xx-xxxx-x.amazonaws.com
            path: /
      restartPolicy: Never
