---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mistral-api
  namespace: stackstorm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mistral-api
    spec:
      containers:
      - name: mistral-api
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ST2_SERVICE
          value: mistral-api
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: rabbitmq }
        - configMapRef: { name: postgres }
        ports:
        - containerPort: 8989

---
kind: Service
apiVersion: v1
metadata:
  name: mistral-api
  namespace: stackstorm
spec:
  selector:
    app: mistral-api
  ports:
  - protocol: TCP
    port: 8989
