---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mistral-server
  namespace: stackstorm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mistral-server
    spec:
      containers:
      - name: mistral-server
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ST2_SERVICE
          value: mistral-server
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: rabbitmq }
        - configMapRef: { name: postgres }
