---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: st2actionrunner
  namespace: stackstorm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: st2actionrunner
    spec:
      containers:
      - name: st2actionrunner
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ST2_SERVICE
          value: st2actionrunner
        - name: ST2_ACTION_AUTH_URL
          value: http://st2auth:9100/
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: rabbitmq }
        - configMapRef: { name: postgres }
        volumeMounts:
        - name: st2-packs
          mountPath: /opt/stackstorm/packs
        - name: st2-virtualenvs
          mountPath: /opt/stackstorm/virtualenvs
      volumes:
      - name: st2-packs
        nfs:
          server: fs-xxxxxxxx.efs.xx-xxxx-x.amazonaws.com
          path: /volumes/static/st2-packs
      - name: st2-virtualenvs
        nfs:
          server: fs-xxxxxxxx.efs.xx-xxxx-x.amazonaws.com
          path: /volumes/static/st2-virtualenvs
